export const minDate = new Date('1985/01/01');
export const maxDate = new Date('2020/01/01');
export const categories = [
  {
    'name': 'Abuse of Authority',
    'subcategories': [
      'Arrest/D. A. T.',
      'Arrest/Onlooker',
      'Body cavity searches',
      'Detention',
      'Electronic device information deletion',
      'Entry of premises',
      'Failed to Obtain Language Interpretation',
      'Failure to provide RTKA card',
      'Forcible removal to hospital',
      'Frisk',
      'Frisk and/or search',
      'Gun drawn',
      'Gun pointed',
      'Gun pointed/gun drawn',
      'Improper dissemination of medical info',
      'Interference with recording',
      'Other',
      'Person searched',
      'Photography/Videography',
      'Premise searched',
      'Premises entered and/or searched',
      'Property damaged',
      'Property seized',
      'Question',
      'Question and/or stop',
      'Questioned immigration status',
      'Refusal to obtain medical treatment',
      'Refusal to process civilian complaint',
      'Refusal to provide name',
      'Refusal to provide name/shield number',
      'Refusal to provide shield number',
      'Refusal to show arrest warrant',
      'Refusal to show search warrant',
      'Retaliatory arrest',
      'Retaliatory summons',
      'Search (of person)',
      'Search of Premises',
      'Search of recording device',
      'Seizure of property',
      'Sexual misconduct (Sexual Harassment, Gesture)',
      'Sexual misconduct (Sexual Harassment, Verbal)',
      'Sexual misconduct (Sexual/Romantic Proposition)',
      'Sexual misconduct (Sexual Humiliation)',
      'Sh Refuse Cmp',
      'Stop',
      'Strip-searched',
      'Threat of arrest',
      'Threat of force (verbal or physical)',
      'Threat of summons',
      'Threat re: removal to hospital',
      'Threat to damage/seize property',
      'Threat to notify ACS',
      'Threat to property',
      'Vehicle search',
      'Vehicle Searched',
      'Vehicle stop',
    ],
  },
  {
    'name': 'Discourtesy',
    'subcategories': [
      'Action',
      'Curse',
      'Demeanor/tone',
      'Gay/Lesbian Slur',
      'Gesture',
      'Nasty Words',
      'Other',
      'Profane gesture',
      'Rude gesture',
      'Sexist remark',
      'Word',
    ],
  },
  {
    'name': 'Force',
    'subcategories': [
      'Animal',
      'Beat',
      'Chokehold',
      'Dragged/Pulled',
      'Flashlight as club',
      'Gun as club',
      'Gun fired',
      'Gun Pointed',
      'Handcuffs too tight',
      'Hit against inanimate object',
      'Mace',
      'Nightstick as club (incl asp & baton)',
      'Nightstick/Billy/Club',
      'Nonlethal restraining device',
      'Other',
      'Other blunt instrument as a club',
      'Pepper spray',
      'Physical force',
      'Police shield',
      'Punch/Kick',
      'Push/Shove',
      'Radio as club',
      'Restricted breathing',
      'Slap',
      'Vehicle',
    ],
  },
  {
    'name': 'Offensive Language',
    'subcategories': [
      'Black',
      'Ethnicity',
      'Gender',
      'Gender Identity',
      'Hispanic',
      'Jewish',
      'Oriental',
      'Other',
      'Other - Ethnic Slur',
      'Other Asian',
      'Physical disability',
      'Race',
      'Religion',
      'Sexual orientation',
      'White',
    ],
  },
];
export const ethnicities = [
  "American Indian",
  "Asian",
  "Black",
  "Hispanic",
  "White",
  "Other Race",
]
export const genders = [
  "Female",
  "Male",
  "Gender non-conforming",
  "Transman (FTM)",
  "Transwoman (MTF)",
]
export const officerGenders = ['Female', 'Male'];
export const ageGroups = [
  "0:17",
  "18:24",
  "25:34",
  "35:44",
  "45:54",
  "55:64",
  "65:101",
];
export const conclusions = [
  'Substantiated (Charges)',
  'Substantiated (Command Discipline)',
  'Substantiated (Command Discipline A)',
  'Substantiated (Command Discipline B)',
  'Substantiated (Command Lvl Instructions)',
  'Substantiated (Formalized Training)',
  'Substantiated (Instructions)',
  'Substantiated (MOS Unidentified)',
  'Substantiated (No Recommendations)',
  'Exonerated',
  'Unsubstantiated',
];