export const minDate = new Date('1985/01/01');
export const maxDate = new Date('2020/01/01');
export const categories = [
  {
    'name': 'Abuse of Authority',
    'subcategories': [
      'Arrest/D. A. T.',
      'Arrest/Onlooker',
      'Body cavity searches',
      'Detention',
      'Electronic device information deletion',
      'Entry of premises',
      'Failed to Obtain Language Interpretation',
      'Failure to provide RTKA card',
      'Forcible removal to hospital',
      'Frisk',
      'Frisk and/or search',
      'Gun drawn',
      'Gun pointed',
      'Gun pointed/gun drawn',
      'Improper dissemination of medical info',
      'Interference with recording',
      'Other',
      'Person searched',
      'Photography/Videography',
      'Premise searched',
      'Premises entered and/or searched',
      'Property damaged',
      'Property seized',
      'Question',
      'Question and/or stop',
      'Questioned immigration status',
      'Refusal to obtain medical treatment',
      'Refusal to process civilian complaint',
      'Refusal to provide name',
      'Refusal to provide name/shield number',
      'Refusal to provide shield number',
      'Refusal to show arrest warrant',
      'Refusal to show search warrant',
      'Retaliatory arrest',
      'Retaliatory summons',
      'Search (of person)',
      'Search of Premises',
      'Search of recording device',
      'Seizure of property',
      'Sexual misconduct (Sexual Harassment, Gesture)',
      'Sexual misconduct (Sexual Harassment, Verbal)',
      'Sexual misconduct (Sexual/Romantic Proposition)',
      'Sexual misconduct (Sexual Humiliation)',
      'Sh Refuse Cmp',
      'Stop',
      'Strip-searched',
      'Threat of arrest',
      'Threat of force (verbal or physical)',
      'Threat of summons',
      'Threat re: removal to hospital',
      'Threat to damage/seize property',
      'Threat to notify ACS',
      'Threat to property',
      'Vehicle search',
      'Vehicle Searched',
      'Vehicle stop',
    ],
  },
  {
    'name': 'Discourtesy',
    'subcategories': [
      'Action',
      'Curse',
      'Demeanor/tone',
      'Gay/Lesbian Slur',
      'Gesture',
      'Nasty Words',
      'Other',
      'Profane gesture',
      'Rude gesture',
      'Sexist remark',
      'Word',
    ],
  },
  {
    'name': 'Force',
    'subcategories': [
      'Animal',
      'Beat',
      'Chokehold',
      'Dragged/Pulled',
      'Flashlight as club',
      'Gun as club',
      'Gun fired',
      'Gun Pointed',
      'Handcuffs too tight',
      'Hit against inanimate object',
      'Mace',
      'Nightstick as club (incl asp & baton)',
      'Nightstick/Billy/Club',
      'Nonlethal restraining device',
      'Other',
      'Other blunt instrument as a club',
      'Pepper spray',
      'Physical force',
      'Police shield',
      'Punch/Kick',
      'Push/Shove',
      'Radio as club',
      'Restricted breathing',
      'Slap',
      'Vehicle',
    ],
  },
  {
    'name': 'Offensive Language',
    'subcategories': [
      'Black',
      'Ethnicity',
      'Gender',
      'Gender Identity',
      'Hispanic',
      'Jewish',
      'Oriental',
      'Other',
      'Other - Ethnic Slur',
      'Other Asian',
      'Physical disability',
      'Race',
      'Religion',
      'Sexual orientation',
      'White',
    ],
  },
];
export const ethnicities = [
  "American Indian",
  "Asian",
  "Black",
  "Hispanic",
  "White",
  "Other Race",
]
export const genders = [
  "Female",
  "Male",
  "Gender non-conforming",
  "Transman (FTM)",
  "Transwoman (MTF)",
]
export const officerGenders = ['Female', 'Male'];
export const ageGroups = [
  "0:17",
  "18:24",
  "25:34",
  "35:44",
  "45:54",
  "55:64",
  "65:101",
];
export const commands = {
  "001 DET": "001 Detective Squad",
  "001 PCT": "001 Precinct",
  "005 DET": "005 Detective Squad",
  "017 PCT": "005 Precinct",
  "006 DET": "006 Detective Squad",
  "006 PCT": "006 Precinct",
  "007 DET": "007 Detective Squad",
  "007 PCT": "007 Precinct",
  "009 DET": "009 Detective Squad",
  "TB DT04": "009 Precinct",
  "010 DET": "010 Detective Squad",
  "010 PCT": "010 Precinct",
  "013 DET": "013 Detective Squad",
  "013 PCT": "013 Precinct",
  "017 DET": "017 Detective Squad",
  "005 PCT": "017 Precinct",
  "019 DET": "019 Detective Squad",
  "019 PCT": "019 Precinct",
  "020 DET": "020 Detective Squad",
  "020 PCT": "020 Precinct",
  "023 DET": "023 Detective Squad",
  "023 PCT": "023 Precinct",
  "024 DET": "024 Detective Squad",
  "024 PCT": "024 Precinct",
  "025 DET": "025 Detective Squad",
  "107 PCT": "025 Precinct",
  "026 DET": "026 Detective Squad",
  "026 PCT": "026 Precinct",
  "028 DET": "028 Detective Squad",
  "028 PCT": "028 Precinct",
  "030 DET": "030 Detective Squad",
  "030 PCT": "030 Precinct",
  "032 DET": "032 Detective Squad",
  "032 PCT": "032 Precinct",
  "033 DET": "033 Detective Squad",
  "033 PCT": "033 Precinct",
  "034 DET": "034 Detective Squad",
  "034 PCT": "034 Precinct",
  "040 DET": "040 Detective Squad",
  "040 PCT": "040 Precinct",
  "041 DET": "041 Detective Squad",
  "041 PCT": "041 Precinct",
  "042 DET": "042 Detective Squad",
  "042 PCT": "042 Precinct",
  "043 DET": "043 Detective Squad",
  "043 PCT": "043 Precinct",
  "044 DET": "044 Detective Squad",
  "044 PCT": "044 Precinct",
  "045 DET": "045 Detective Squad",
  "045 PCT": "045 Precinct",
  "046 DET": "046 Detective Squad",
  "046 PCT": "046 Precinct",
  "047 DET": "047 Detective Squad",
  "047 PCT": "047 Precinct",
  "048 DET": "048 Detective Squad",
  "048 PCT": "048 Precinct",
  "049 DET": "049 Detective Squad",
  "049 PCT": "049 Precinct",
  "050 DET": "050 Detective Squad",
  "050 PCT": "050 Precinct",
  "052 DET": "052 Detective Squad",
  "052 PCT": "052 Precinct",
  "060 DET": "060 Detective Squad",
  "SRG 4": "060 Precinct",
  "061 DET": "061 Detective Squad",
  "062 PCT": "061 Precinct",
  "062 DET": "062 Detective Squad",
  "061 PCT": "062 Precinct",
  "063 DET": "063 Detective Squad",
  "063 PCT": "063 Precinct",
  "066 DET": "066 Detective Squad",
  "066 PCT": "066 Precinct",
  "067 DET": "067 Detective Squad",
  "067 PCT": "067 Precinct",
  "068 DET": "068 Detective Squad",
  "068 PCT": "068 Precinct",
  "069 DET": "069 Detective Squad",
  "069 PCT": "069 Precinct",
  "070 DET": "070 Detective Squad",
  "077 PCT": "070 Precinct",
  "071 DET": "071 Detective Squad",
  "071 PCT": "071 Precinct",
  "072 DET": "072 Detective Squad",
  "072 PCT": "072 Precinct",
  "073 DET": "073 Detective Squad",
  "073 PCT": "073 Precinct",
  "075 DET": "075 Detective Squad",
  "075 PCT": "075 Precinct",
  "076 DET": "076 Detective Squad",
  "076 PCT": "076 Precinct",
  "077 DET": "077 Detective Squad",
  "070 PCT": "077 Precinct",
  "078 DET": "078 Detective Squad",
  "078 PCT": "078 Precinct",
  "079 DET": "079 Detective Squad",
  "079 PCT": "079 Precinct",
  "081 DET": "081 Detective Squad",
  "081 PCT": "081 Precinct",
  "083 DET": "083 Detective Squad",
  "083 PCT": "083 Precinct",
  "084 DET": "084 Detective Squad",
  "084 PCT": "084 Precinct",
  "088 DET": "088 Detective Squad",
  "088 PCT": "088 Precinct",
  "090 DET": "090 Detective Squad",
  "090 PCT": "090 Precinct",
  "094 DET": "094 Detective Squad",
  "094 PCT": "094 Precinct",
  "100 DET": "100 Detective Squad",
  "100 PCT": "100 Precinct",
  "101 DET": "101 Detective Squad",
  "101 PCT": "101 Precinct",
  "102 DET": "102 Detective Squad",
  "102 PCT": "102 Precinct",
  "103 DET": "103 Detective Squad",
  "103 PCT": "103 Precinct",
  "104 DET": "104 Detective Squad",
  "104 PCT": "104 Precinct",
  "105 DET": "105 Detective Squad",
  "105 PCT": "105 Precinct",
  "106 DET": "106 Detective Squad",
  "106 PCT": "106 Precinct",
  "107 DET": "107 Detective Squad",
  "109 PCT": "107 Precinct",
  "108 DET": "108 Detective Squad",
  "108 PCT": "108 Precinct",
  "109 DET": "109 Detective Squad",
  "025 PCT": "109 Precinct",
  "110 DET": "110 Detective Squad",
  "110 PCT": "110 Precinct",
  "111 DET": "111 Detective Squad",
  "111 PCT": "111 Precinct",
  "112 DET": "112 Detective Squad",
  "112 PCT": "112 Precinct",
  "113 DET": "113 Detective Squad",
  "113 PCT": "113 Precinct",
  "114 DET": "114 Detective Squad",
  "114 PCT": "114 Precinct",
  "115 DET": "115 Detective Squad",
  "115 PCT": "115 Precinct",
  "120 DET": "120 Detective Squad",
  "120 PCT": "120 Precinct",
  "121 DET": "121 Detective Squad",
  "121 PCT": "121 Precinct",
  "122 DET": "122 Detective Squad",
  "122 PCT": "122 Precinct",
  "123 DET": "123 Detective Squad",
  "123 PCT": "123 Precinct",
  "ADM DIV": "Administration Division",
  "ADM SUP": "Administrative Support Division",
  "A P DIV": "Applicant Processing Division",
  "A&E": "Arson and Explosion Squad",
  "AUTO CR": "Auto Crime Division",
  "AUX P.S": "Auxiliary Police Section",
  "AV.UNIT": "Aviation Unit",
  "BARRIER": "Barrier Section",
  "BOMB SQ": "Bomb Squad",
  "BX CT": "Bronx Court Section",
  "BXROBSQ": "Bronx Robbery Squad",
  "SVD Z2": "Bronx Special Victims Squad",
  "BKLN CT": "Brooklyn Court Section",
  "BKROBSQ": "Brooklyn Robbery Squad",
  "BM SEC": "Building Maintenance Section",
  "BUS UT": "Bus Unit",
  "BX SVS": "BX SVS",
  "C C SQD": "C C SQD",
  "C O B": "C O B",
  "CAB COD": "CAB COD",
  "C E D": "Career Development Division",
  "CD EPES": "CD EPES",
  "DB CID": "Central Investigation and Research Division",
  "CPK DET": "Central Park Detective Squad",
  "CPK PCT": "Central Park Precinct",
  "CEN REC": "Central Records Division",
  "CD IRS": "Chief of Department Investigation Review Section",
  "CD OFF": "Chief of Department Office",
  "CD OP/U": "Chief of Department Operations Unit",
  "COD SAS": "Chief of Department Strategic Analysis Section",
  "CT UNIT": "City Wide Counterterrorism Unit",
  "COMMDIV": "Communications Division",
  "C A B": "Community Affairs Bureau",
  "CA JVJD": "Community Affairs Bureau Juvenile Justice Division",
  "CON ADM": "Contract Administration Unit",
  "CT BUR": "Counterterrorism Bureau",
  "CTERRDV": "Counterterrorism Division",
  "CT LMSI": "Counterterrorism Lower Manhattan Security Initiative",
  "C/PRV D": "Crime Prevention Division",
  "C/SCENE": "Crime Scene Unit",
  "INT CIS": "Criminal Intelligence Section",
  "CRJ BUR": "Criminal Justice Bureau",
  "CRS/AU": "Criminal Records Section (Aided Unit)",
  "C R C": "Critical Response Command",
  "DA BKLN": "DA BKLN",
  "DA BX": "DA BX",
  "DA NY": "DA NY",
  "DA QNS": "DA QNS",
  "DA SI": "DA SI",
  "DB SID": "DB SID",
  "DBCR Z1": "DBCR Z1",
  "DCSC": "DCSC",
  "DPT INV": "Department of Investigation Squad",
  "DC ADM": "Deputy Commissioner Administration",
  "DCA C U": "Deputy Commissioner Administration Ceremonial Unit",
  "DCCP": "Deputy Commissioner Collaborative Policing",
  "DC DAO": "Deputy Commissioner Department Advocate Office",
  "DC EEO": "Deputy Commissioner Equal Employment Opportunity",
  "DC LABR": "Deputy Commissioner Labor Relations",
  "D C M B": "Deputy Commissioner Management and Budget",
  "DC OPER": "Deputy Commissioner of Operations",
  "D C P I": "Deputy Commissioner of Public Information",
  "DC TRNG": "Deputy Commissioner of Training",
  "DC TRL": "Deputy Commissioner of Trials",
  "DBBX": "Detective Borough Bronx",
  "DB BXHM": "Detective Borough Bronx Homicide Squad",
  "DBBN": "Detective Borough Brooklyn North",
  "DB BNHM": "Detective Borough Brooklyn North Homicide Squad",
  "DBBN OP": "Detective Borough Brooklyn North Operations",
  "DBBS OP": "Detective Borough Brooklyn Operations",
  "DBBS": "Detective Borough Brooklyn South",
  "DB BSHM": "Detective Borough Brooklyn South Homicide Squad",
  "DBBKZ10": "Detective Borough Brooklyn Zone 10",
  "DBBKZ11": "Detective Borough Brooklyn Zone 11",
  "DBBKZ13": "Detective Borough Brooklyn Zone 13",
  "DBBKZ14": "Detective Borough Brooklyn Zone 14",
  "DBBKZ21": "Detective Borough Brooklyn Zone 21",
  "DBBKZ22": "Detective Borough Brooklyn Zone 22",
  "DBMN": "Detective Borough Manhattan North",
  "DBMN OP": "Detective Borough Manhattan North Operations",
  "DBMS": "Detective Borough Manhattan South",
  "DBMS OP": "Detective Borough Manhattan South Operations",
  "DBM ZN2": "Detective Borough Manhattan Zone 2",
  "DBM ZN6": "Detective Borough Manhattan Zone 6",
  "DBQN": "Detective Borough Queens North",
  "DBQS": "Detective Borough Queens South",
  "DBQS OP": "Detective Borough Queens South Operations",
  "DBSI": "Detective Borough Staten Island",
  "DET BUR": "Detective Bureau",
  "BK SVS": "Detective Bureau Brooklyn Special Victims Squad",
  "DB CRD": "Detective Bureau Central Robbery Division",
  "DB FCTF": "Detective Bureau Financial Crimes Task Force",
  "DB GLD": "Detective Bureau Grand Larceny Division",
  "DB HATE": "Detective Bureau Hate Crimes Task Force",
  "DB LPS": "Detective Bureau Latent Print Section",
  "DB MNHM": "Detective Bureau Manhattan North Homicide Squad",
  "DB MSHM": "Detective Bureau Manhattan South Homicide Squad",
  "M SVS": "Detective Bureau Manhattan Special Victims Squad",
  "DB QNHM": "Detective Bureau Queens Homicide Squad",
  "DBQ Z19": "Detective Bureau Queens Zone 19",
  "DB SVD": "Detective Bureau Special Victims Division",
  "DB TSIU": "Detective Bureau Transit Special Investigation Unit",
  "DIS CTL": "Disorder Control Unit",
  "DR.ED&T": "Driver Education and Training Unit",
  "D-E T/F": "Drug Enforcement Task Force",
  "EM OPS": "Emergency Operations Center",
  "ESS 01": "Emergency Service Squad 01",
  "ESS 02": "Emergency Service Squad 02",
  "ESS 03": "Emergency Service Squad 03",
  "ESS 04": "Emergency Service Squad 04",
  "ESS 05": "Emergency Service Squad 05",
  "ESS 06": "Emergency Service Squad 06",
  "ESS 07": "Emergency Service Squad 07",
  "ESS 08": "Emergency Service Squad 08",
  "ESS 09": "Emergency Service Squad 09",
  "ESS 10": "Emergency Service Squad 10",
  "E S U": "Emergency Service Unit",
  "ESU CAN": "Emergency Service Unit Canine Team",
  "EMP REL": "Employee Relations Section",
  "EQP SEC": "Equipment Section",
  "FM DIV": "Facilities Management Division",
  "FIN MGT": "Financial Management Division",
  "F.T.S.": "Firearms and Tactics Section",
  "F S S": "Firearms Suppression Division",
  "1ST D.C": "First Deputy Commissioner",
  "FLT SVC": "Fleet Services Division",
  "FORCEID": "Force Investigation Division",
  "DB FID": "Forensics Investigations Division",
  "DB FED": "Fugitive Enforcement Division",
  "GANG DV": "Gang Division",
  "GANG BX": "Gang Squad Bronx",
  "GANG BN": "Gang Squad Brooklyn North",
  "GANG BS": "Gang Squad Brooklyn South",
  "GANG MN": "Gang Squad Manhattan North",
  "GANG MS": "Gang Squad Manhattan South",
  "GANG QN": "Gang Squad Queens North",
  "GANG QS": "Gang Squad Queens South",
  "GANG SI": "Gang Squad Staten Island",
  "DB GVSD": "Gun Violence Suppression Division",
  "GVSD Z1": "Gun Violence Suppression Division Zone 01",
  "GVSD Z2": "Gun Violence Suppression Division Zone 02",
  "HARBOR": "Harbor Unit",
  "HQ SEC": "Headquarters Security",
  "HWY 01": "Highway Unit 01",
  "HWY 02": "Highway Unit 02",
  "HWY 03": "Highway Unit 03",
  "HWY 05": "Highway Unit 05",
  "HBXQIRT": "Housing Borough Bronx/Queens Impact Response Team",
  "HBK IRT": "Housing Borough Brooklyn Impact Response Team",
  "HBM IRT": "Housing Borough Manhattan Impact Response Team",
  "H BX/Q": "Housing Bronx/Queens",
  "H BKLYN": "Housing Brooklyn",
  "HSG BUR": "Housing Bureau",
  "H INV U": "Housing Investigations Unit",
  "H MAN": "Housing Manhattan",
  "H SP OP": "Housing Special Operations Section",
  "I T S D": "I T S D",
  "ID SECT": "Identification Section",
  "INT EPU": "INT EPU",
  "INT UOU": "INT UOU",
  "INT BUR": "Intelligence Bureau",
  "INT OAS": "Intelligence Operations and Analysis Section",
  "INT PSS": "Intelligence Public Security Section",
  "I.A.B.": "Internal Affairs Bureau",
  "INV SUP": "Investigative Support Division",
  "JB/R/TF": "Joint Bank Robbery Task Force",
  "JT T/F": "Joint Terrorism Task Force",
  "JUV CRM": "Juvenile Crime Section",
  "LDS TRN": "Leadership Training Section",
  "L.I.M.S": "Leave Integrity Management Section",
  "LEG BUR": "Legal Bureau",
  "LIC DIV": "License Division",
  "L S S D": "Life Safety Systems Division",
  "MC/SQD": "Major Case Squad",
  "MAN CT": "Manhattan Court Section",
  "MNROBSQ": "Manhattan Robbery Squad",
  "MB SSZN": "MB SSZN",
  "MED DIV": "Medical Division",
  "MTN DET": "Midtown North Detective Squad",
  "MTN PCT": "Midtown North Precinct",
  "MTS DET": "Midtown South Detective Squad",
  "MTS PCT": "Midtown South Precinct",
  "M E L D": "Military and Extended Leave Desk",
  "MP SQD": "Missing Person Squad",
  "MOUNTED": "Mounted Unit",
  "NARCBBX": "Narcotics Borough Bronx",
  "NARCBBN": "Narcotics Borough Brooklyn North",
  "NARCBBS": "Narcotics Borough Brooklyn South",
  "NARCBMN": "Narcotics Borough Manhattan North",
  "NARCBMS": "Narcotics Borough Manhattan South",
  "NARCBQN": "Narcotics Borough Queens North",
  "NARCBQS": "Narcotics Borough Queens South",
  "NARCBSI": "Narcotics Borough Staten Island",
  "NAR DIV": "Narcotics Division",
  "I T B": "Office of Information Technology",
  "OFSCSRG": "OFSCSRG",
  "OMAP": "OMAP",
  "O C C B": "Organized Crime Control Bureau",
  "STR FOR": "Organized Crime Drug Enforcement Strike Force",
  "DB CEIS": "Organized Crime Investigation Division",
  "PBBX": "Patrol Borough Bronx",
  "PBBX SU": "Patrol Borough Bronx Specialized Units",
  "PBBN": "Patrol Borough Brooklyn North",
  "PBBN SU": "Patrol Borough Brooklyn North Specialized Units",
  "PBBS": "Patrol Borough Brooklyn South",
  "PBBS SU": "Patrol Borough Brooklyn South Specialized Units",
  "PBMN": "Patrol Borough Manhattan North",
  "PBMN SU": "Patrol Borough Manhattan North Specialized Units",
  "PBMS": "Patrol Borough Manhattan South",
  "PBMS SU": "Patrol Borough Manhattan South Specialized Units",
  "PBQ/N": "Patrol Borough Queens North",
  "PBQN SU": "Patrol Borough Queens North Specialized Units",
  "PBQ/S": "Patrol Borough Queens South",
  "PBQS SU": "Patrol Borough Queens South Specialized Units",
  "PBSI": "Patrol Borough Staten Island",
  "PBSI SU": "Patrol Borough Staten Island Specialized Units",
  "PB EMD": "Patrol Bureau Employee Management Division",
  "P S B": "Patrol Services Bureau",
  "TV UNIT": "Patrol Services Bureau Movie and T.V. Unit",
  "PSB RMS": "Patrol Services Bureau Resource Management Section",
  "PAY&BEN": "Payroll and Benefits Division",
  "PER BUR": "Personnel Bureau",
  "PB POS": "Personnel Orders Section",
  "PLT MGT": "Plant Management Unit",
  "POL ACD": "Police Academy Payroll and Roll Call",
  "P C C U": "Police Cadet Corps Unit",
  "P C O": "Police Commissioner Office",
  "PCO L U": "Police Commissioner Office Liaison Unit",
  "POL LAB": "Police Laboratory",
  "POL PEN": "Police Pension Fund",
  "PSA 1": "Police Service Area 1",
  "PSA 2": "Police Service Area 2",
  "PSA 3": "Police Service Area 3",
  "PSA 4": "Police Service Area 4",
  "PSA 5": "Police Service Area 5",
  "PSA 6": "Police Service Area 6",
  "PSA 7": "Police Service Area 7",
  "PSA 8": "Police Service Area 8",
  "PSA 9": "Police Service Area 9",
  "PRINTS": "Printing Section",
  "PROPCLK": "Property Clerk Division",
  "PSB IES": "PSB IES",
  "PI&REQ": "Public Inquiry and Request Section",
  "R M D": "Quality Assurance",
  "QM SEC": "Quartermaster Section",
  "QNS CT": "Queens Court Section",
  "QNROBSQ": "Queens Robbery Squad",
  "Q SVS": "Queens Special Victims Squad",
  "RTCC": "Real Time Crime Center",
  "REC TNG": "Recruit Training Section",
  "RM BUR": "Risk Management Bureau",
  "RMB QAD": "RMB QAD",
  "S P I S": "S P I S",
  "S T D": "S T D",
  "SS DIV": "School Safety Division",
  "SSD INV": "School Safety Investigations",
  "QB SSZN": "School Safety Queens Brooklyn Staten Island Zone",
  "SP FRDS": "Special Fraud Squad",
  "S O D": "Special Operations Division",
  "SPL TRN": "Specialized Training Section",
  "SRG": "SRG",
  "STAFFSV": "Staff Services Section",
  "S.I. CT": "Staten Island Court Section",
  "SRG 1": "Strategic Response Group 1",
  "SRG 2": "Strategic Response Group 2",
  "SRG 3": "Strategic Response Group 3",
  "060 PCT": "Strategic Response Group 4",
  "SRG 5": "Strategic Response Group 5",
  "S S B": "Support Services Bureau",
  "SVD Z1": "SVD Z1",
  "SVD Z3": "SVD Z3",
  "TAXI SQ": "Taxi Squad",
  "TAXI UT": "Taxi Unit",
  "T.A.R.U": "Technical Assistance and Response Unit",
  "TB LIAS": "Transit Authority Liaison",
  "TB MANH": "Transit Borough Manhattan",
  "TB": "Transit Bureau",
  "TB ATU": "Transit Bureau Anti-Terrorism Unit",
  "TB BK": "Transit Bureau Borough Brooklyn",
  "TB BKTF": "Transit Bureau Borough Brooklyn Task Force",
  "TB BX/Q": "Transit Bureau Bronx/Queens",
  "TB BQTF": "Transit Bureau Bronx/Queens Task Force",
  "TB CAN": "Transit Bureau Canine Unit",
  "TB VTF": "Transit Bureau Citywide Vandals Task Force",
  "TB C/AN": "Transit Bureau Crime Analysis",
  "TB DT01": "Transit Bureau District 1",
  "TB DT11": "Transit Bureau District 11",
  "TB DT12": "Transit Bureau District 12",
  "TB DT02": "Transit Bureau District 2",
  "TB DT33": "Transit Bureau District 20",
  "TB DT23": "Transit Bureau District 23",
  "TB DT20": "Transit Bureau District 3",
  "TB DT30": "Transit Bureau District 30",
  "TB DT32": "Transit Bureau District 32",
  "TB DT03": "Transit Bureau District 33",
  "TB DT34": "Transit Bureau District 34",
  "009 PCT": "Transit Bureau District 4",
  "C O S U": "Transit Bureau Homeless Outreach",
  "TB INV": "Transit Bureau Investigation Unit",
  "TB M/TF": "Transit Bureau Manhattan Task Force",
  "TB RESP": "Transit Bureau Response Team",
  "TB SOD": "Transit Bureau Special Operations District",
  "TRP BUR": "Transportation Bureau",
  "CW T TF": "Transportation Bureau Citywide Traffic",
  "HWY DST": "Transportation Bureau Highway District",
  "TRB TED": "Transportation Bureau Traffic Enforcement District",
  "TRF OPS": "Transportation Bureau Traffic Operations District",
  "PA UPTU": "Uniformed Promotions Training Unit",
  "VICE": "VICE Enforcement",
  "WARRSEC": "Warrant Section",
  "WTC CMD": "World Trade Center Command",
  "YTH SS": "Youth Services Section",
};

export const ranks = [
  "Police Officer",
  "Sergeant",
  "Detective",
  "Lieutenant",
  "Captain",
  "Deputy Inspector",
  "Inspector",
  "Chiefs and other ranks",
];

export const conclusions = [
  {
    'name': 'Substantiated',
    'subcategories': [
      'Charges',
      'Command Discipline',
      'Command Discipline A',
      'Command Discipline B',
      'Command Lvl Instructions',
      'Formalized Training',
      'Instructions',
      'MOS Unidentified',
      'No Recommendations',
    ],
  },
  {
    'name': 'Exonerated',
  },
  {
    'name': 'Unsubstantiated',
  }
];